# Generated by Django 5.1.1 on 2024-10-05 16:32

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birthday',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
