# Generated by Django 5.1.1 on 2024-10-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_teacher_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetoteacher',
            name='rate',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
