# Generated by Django 5.1.1 on 2025-02-24 08:19

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_image_customuser_recovery_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'مربی', 'verbose_name_plural': 'مربیان'},
        ),
        migrations.AlterModelOptions(
            name='teachersignupform',
            options={'verbose_name': 'فرم ثبت\u200cنام مربی', 'verbose_name_plural': 'فرم\u200cهای ثبت\u200cنام مربیان'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='code_meli',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'زن'), ('male', 'مرد')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='مدیر سیستم'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='ابرکاربر'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='recovery_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='کد بازیابی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('default', 'کاربر عادی'), ('teacher', 'مربی'), ('student', 'هنرجو')], max_length=20, null=True, verbose_name='وضعیت کاربر'),
        ),
        migrations.AlterField(
            model_name='ratetoteacher',
            name='rate',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='ratetoteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_rate', to='accounts.teacher', verbose_name='معلم'),
        ),
        migrations.AlterField(
            model_name='ratetoteacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='average_rate',
            field=models.FloatField(default=0.0, verbose_name='امتیاز میانگین'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birthday',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='code_meli',
            field=models.CharField(max_length=15, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, upload_to='teacher', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='teachersignupform',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='تأیید شده'),
        ),
        migrations.AlterField(
            model_name='teachersignupform',
            name='l_name',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='teachersignupform',
            name='massage',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='teachersignupform',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='teachersignupform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_form', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
