# Generated by Django 5.1.1 on 2025-02-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratetoteacher',
            options={'verbose_name': 'امتیاز به  مربی', 'verbose_name_plural': 'امتیاز به مربیان'},
        ),
    ]
