# Generated by Django 5.1.1 on 2025-03-29 00:11

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_commentteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentteacher',
            name='create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ساخته شده'),
        ),
    ]
