# Generated by Django 5.1.1 on 2025-03-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_commentteacher_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='profile/default-avatar.jpg', null=True, upload_to='profile', verbose_name='تصویر پروفایل'),
        ),
    ]
