# Generated by Django 5.1.1 on 2024-12-12 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_teacher_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetoteacher',
            name='rate',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='ratetoteacher',
            constraint=models.UniqueConstraint(fields=('user', 'teacher'), name='unique_rate_per_user_teacher'),
        ),
    ]
