# Generated by Django 5.1.1 on 2024-12-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_ratetoteacher_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='average_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
