# Generated by Django 5.1.1 on 2024-10-05 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'دختر'), ('male', 'پسر')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('private', 'خصوصی'), ('public', 'عمومی'), ('mid', 'نیمه خصوصی')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('female', 'دختر'), ('male', 'پسر')], max_length=10, null=True)),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('address', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('public', 'شیفت عمومی'), ('education', 'شیفت آموزش')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('start_clock', models.TimeField()),
                ('end_clock', models.TimeField()),
                ('active', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=1, max_digits=7)),
                ('teacher', models.ForeignKey(limit_choices_to={'status': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_classes', to=settings.AUTH_USER_MODEL)),
                ('course_start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_start', to='pool.createclass')),
            ],
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_paid', to='pool.classes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_paid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='createclass',
            name='pool',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'education'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pool_course', to='pool.pool'),
        ),
        migrations.CreateModel(
            name='StartClass',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='course', serialize=False, to='pool.classes')),
                ('limit_register', models.PositiveIntegerField(default=3)),
                ('student', models.ManyToManyField(blank=True, limit_choices_to={'status': 'stu'}, related_name='class_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
