# Generated by Django 5.1.1 on 2025-01-09 20:09

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pool_images/'),
        ),
        migrations.AddField(
            model_name='startclass',
            name='register_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classes',
            name='end',
            field=django_jalali.db.models.jDateField(blank=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='classes',
            name='start',
            field=django_jalali.db.models.jDateField(null=True),
        ),
        migrations.AlterField(
            model_name='createclass',
            name='status',
            field=models.CharField(choices=[('public', 'عمومی'), ('mid', 'نیمه خصوصی')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paid',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_paid', to='pool.classes'),
        ),
        migrations.AlterField(
            model_name='startclass',
            name='student',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'student'}, related_name='class_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PrivateClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateField()),
                ('start_time', models.TimeField()),
                ('price', models.PositiveIntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paid',
            name='private_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='private_class_paid', to='pool.privateclass'),
        ),
        migrations.CreateModel(
            name='RequestPrivateClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.PositiveSmallIntegerField(default=1)),
                ('massage', models.TextField()),
                ('acceptation', models.BooleanField(default=False)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_private', to='pool.pool')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'status': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_private', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_private', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='privateclass',
            name='class_requested',
            field=models.ForeignKey(limit_choices_to={'acceptation': True}, on_delete=django.db.models.deletion.CASCADE, related_name='class_requested', to='pool.requestprivateclass'),
        ),
    ]
