# Generated by Django 5.1.1 on 2024-10-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
