# Generated by Django 5.1.1 on 2025-01-10 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_classes_discount_pool_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='createclass',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'زنانه'), ('male', 'مردانه')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='requestprivateclass',
            name='user',
            field=models.ForeignKey(limit_choices_to=models.Q(('status__in', ['default', 'student']), ('status__isnull', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='user_private', to=settings.AUTH_USER_MODEL),
        ),
    ]
