# Generated by Django 5.1.1 on 2024-10-06 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_alter_classes_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='startclass',
            name='register_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='startclass',
            name='student',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'student'}, related_name='class_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
