# Generated by Django 5.1.1 on 2025-01-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_alter_createclass_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'زنانه'), ('male', 'مردانه')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
