# Generated by Django 5.1.1 on 2024-10-09 07:35

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_startclass_register_count_alter_startclass_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='end',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='classes',
            name='start',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
