# Generated by Django 5.1.1 on 2025-01-10 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_alter_pool_gender_alter_privateclass_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateclass',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('status__in', ['default', 'student']), ('status__isnull', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
