# Generated by Django 5.1.1 on 2025-01-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_alter_privateclass_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateclass',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
