# Generated by Django 5.1.1 on 2024-10-09 08:44

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_alter_classes_end_alter_classes_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='end',
            field=django_jalali.db.models.jDateField(blank=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='start',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
