# Generated by Django 5.1.1 on 2024-11-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0006_alter_classes_end_alter_classes_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pool_images/'),
        ),
    ]
