# Generated by Django 5.1.1 on 2025-01-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0006_privateclass_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestprivateclass',
            name='acceptation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
