# Generated by Django 5.1.1 on 2025-01-19 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0007_alter_requestprivateclass_acceptation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='privateclass',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_class_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
