# Generated by Django 5.1.1 on 2025-01-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0008_privateclass_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid',
            name='private_class',
        ),
    ]
