# Generated by Django 5.1.1 on 2025-02-09 21:02

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0009_remove_paid_private_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('start', django_jalali.db.models.jDateTimeField()),
                ('end', django_jalali.db.models.jDateTimeField()),
                ('discount', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
