# Generated by Django 5.1.1 on 2025-02-24 10:16

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0010_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'کلاس', 'verbose_name_plural': 'کلاس\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کدهای تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='createclass',
            options={'verbose_name': 'کد کلاس', 'verbose_name_plural': 'کد کلاس ها'},
        ),
        migrations.AlterModelOptions(
            name='paid',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='pool',
            options={'verbose_name': 'استخر', 'verbose_name_plural': 'استخرها'},
        ),
        migrations.AlterModelOptions(
            name='privateclass',
            options={'verbose_name': 'کلاس خصوصی', 'verbose_name_plural': 'کلاس\u200cهای خصوصی'},
        ),
        migrations.AlterModelOptions(
            name='requestprivateclass',
            options={'verbose_name': 'درخواست کلاس خصوصی', 'verbose_name_plural': 'درخواست\u200cهای کلاس خصوصی'},
        ),
        migrations.AlterModelOptions(
            name='startclass',
            options={'verbose_name': 'شروع کلاس', 'verbose_name_plural': 'شروع کلاس\u200cها'},
        ),
        migrations.AlterField(
            model_name='classes',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='course_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_start', to='pool.createclass', verbose_name='شروع دوره'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='end',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='end_clock',
            field=models.TimeField(verbose_name='ساعت پایان'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='start',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='start_clock',
            field=models.TimeField(verbose_name='ساعت شروع'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'status': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_classes', to=settings.AUTH_USER_MODEL, verbose_name='مربی'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.PositiveSmallIntegerField(verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='createclass',
            name='course_code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='کد کلاس'),
        ),
        migrations.AlterField(
            model_name='createclass',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'زنانه'), ('male', 'مردانه')], max_length=10, null=True, verbose_name='جنسیت کلاس'),
        ),
        migrations.AlterField(
            model_name='createclass',
            name='pool',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'education'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pool_course', to='pool.pool', verbose_name='استخر'),
        ),
        migrations.AlterField(
            model_name='createclass',
            name='status',
            field=models.CharField(choices=[('public', 'عمومی'), ('mid', 'نیمه خصوصی')], max_length=10, verbose_name='نوع کلاس'),
        ),
        migrations.AlterField(
            model_name='paid',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_paid', to='pool.classes', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='paid',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='paid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_paid', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'زنانه'), ('male', 'مردانه')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pool_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام استخر'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='status',
            field=models.CharField(blank=True, choices=[('public', 'شیفت عمومی'), ('education', 'شیفت آموزش')], max_length=20, null=True, verbose_name='وضعیت استخر'),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='class_requested',
            field=models.ForeignKey(limit_choices_to={'acceptation': True}, on_delete=django.db.models.deletion.CASCADE, related_name='class_requested', to='pool.requestprivateclass', verbose_name='درخواست کلاس'),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='start_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='start_time',
            field=models.TimeField(verbose_name='ساعت شروع'),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_class_teacher', to=settings.AUTH_USER_MODEL, verbose_name='مربی'),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('status__in', ['default', 'student']), ('status__isnull', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_student', to=settings.AUTH_USER_MODEL, verbose_name='هنرجو'),
        ),
        migrations.AlterField(
            model_name='requestprivateclass',
            name='acceptation',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید شده'),
        ),
        migrations.AlterField(
            model_name='requestprivateclass',
            name='massage',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='requestprivateclass',
            name='person',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='تعداد افراد'),
        ),
        migrations.AlterField(
            model_name='requestprivateclass',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_private', to='pool.pool', verbose_name='استخر'),
        ),
        migrations.AlterField(
            model_name='requestprivateclass',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_private', to=settings.AUTH_USER_MODEL, verbose_name='مربی'),
        ),
        migrations.AlterField(
            model_name='requestprivateclass',
            name='user',
            field=models.ForeignKey(limit_choices_to=models.Q(('status__in', ['default', 'student']), ('status__isnull', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='user_private', to=settings.AUTH_USER_MODEL, verbose_name='کاربر درخواست\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='startclass',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='course', serialize=False, to='pool.classes', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='startclass',
            name='limit_register',
            field=models.PositiveIntegerField(default=3, verbose_name='حد ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='startclass',
            name='register_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد ثبت\u200cنام\u200cشده\u200cها'),
        ),
        migrations.AlterField(
            model_name='startclass',
            name='student',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'student'}, related_name='class_student', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموزان'),
        ),
    ]
