# Generated by Django 5.1.1 on 2025-02-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0011_alter_classes_options_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='course_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_start', to='pool.createclass', verbose_name='کد دوره'),
        ),
    ]
