# Generated by Django 5.1.1 on 2025-02-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0012_alter_classes_course_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='مبلغ'),
        ),
    ]
