# Generated by Django 5.1.1 on 2025-02-25 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0013_paid_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateclass',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('status', 'teacher'), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_student', to=settings.AUTH_USER_MODEL, verbose_name='هنرجو'),
        ),
    ]
