# Generated by Django 5.1.1 on 2025-02-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0014_alter_privateclass_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startclass',
            name='course',
            field=models.OneToOneField(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='course', serialize=False, to='pool.classes', verbose_name='دوره'),
        ),
    ]
