# Generated by Django 5.1.1 on 2025-03-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0016_alter_startclass_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='ref_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تراکنش'),
        ),
    ]
