# Generated by Django 5.1.1 on 2025-04-05 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0017_paid_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ پرداخت'),
            preserve_default=False,
        ),
    ]
