# Generated by Django 5.1.1 on 2025-04-09 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0018_paid_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
