# Generated by Django 5.1.1 on 2025-04-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0019_pool_created_at_pool_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='created_at',
        ),
    ]
