# Generated by Django 5.1.1 on 2025-04-09 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0020_remove_pool_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
