# Generated by Django 5.1.1 on 2025-05-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0021_pool_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='authority',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد پیگیری زرین\u200cپال'),
        ),
    ]
