# Generated by Django 5.1.1 on 2025-05-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0022_paid_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='title',
            field=models.CharField(default='روز های زوج', max_length=250),
        ),
    ]
