# Generated by Django 5.1.1 on 2025-03-25 14:16

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pool', '0017_paid_ref_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('discount_amount', models.IntegerField(default=0, verbose_name='مبلغ تخفیف ')),
                ('description', models.CharField(max_length=250, verbose_name='توضیحات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ساخته شده')),
                ('modified_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تغغیر داده شده')),
                ('pool', models.ForeignKey(limit_choices_to={'status': 'public'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pool_tickets', to='pool.pool', verbose_name='استخر')),
            ],
            options={
                'verbose_name': 'بلیط',
                'verbose_name_plural': 'بلیط ها',
            },
        ),
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('code', models.CharField(editable=False, max_length=6, unique=True, verbose_name='کد ورود')),
                ('entrance_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='ساعت ورود')),
                ('exit_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='ساعت خروج')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reserve_tickets', to='ticket.poolticket', verbose_name='بلیط')),
            ],
            options={
                'verbose_name': 'بلیط کاربر',
                'verbose_name_plural': 'بلیط کاربران',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('ref_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تراکنش')),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='ticket.ticketreservation', verbose_name='رزرو')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
    ]
