# Generated by Django 5.1.1 on 2025-03-25 14:18

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolticket',
            name='modified_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تغییر داده شده'),
        ),
    ]
