# Generated by Django 5.1.1 on 2025-03-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_poolticket_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolticket',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ تخفیف '),
        ),
    ]
