# Generated by Django 5.1.1 on 2025-05-14 20:02

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_payment_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=100, unique=True, verbose_name='کد تخفیف')),
                ('active', models.BooleanField(default=False, verbose_name='فعال')),
                ('start', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع')),
                ('end', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پایان')),
                ('discount', models.PositiveSmallIntegerField(verbose_name='درصد تخفیف')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
    ]
