# Generated by Django 5.1.1 on 2025-05-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticketcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
