# Generated by Django 5.1.1 on 2025-05-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_ticketreservation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreservation',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True, verbose_name='کد ورود'),
        ),
    ]
