# Generated by Django 5.1.1 on 2025-05-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_ticketreservation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
