# Generated by Django 5.1.1 on 2025-05-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_payment_sms_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sms_sent',
            field=models.BooleanField(default=False, verbose_name='ارسال sms'),
        ),
        migrations.AlterField(
            model_name='ticketreservation',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
