# Generated by Django 5.1.1 on 2025-06-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_alter_payment_price_alter_payment_sms_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolticket',
            name='per_minute',
            field=models.PositiveIntegerField(default=100, verbose_name='در عوض هر دقیقه بیشتر'),
        ),
    ]
