# Generated by Django 5.1.1 on 2025-06-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_poolticket_per_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation',
            name='closet_code',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='شماره کمد'),
        ),
    ]
